config/routes.rb
Rails.application.routes.draw do
  post 'webhooks/receive'

  devise_for :users

  resources :apps do
    resources :assets do
      get 'download', action: 'download', as: 'download'
    end

    resources :notifications
    resources :versions

    post 'notifications/configure', to: 'notifications#configure_notifications'
    post 'autority/invite', to: 'apps#invite', as: 'autority_invite'

    member do
      get 'settings'
      get 'build'
      post 'build', to: 'apps#jenkins', as: 'trigger_build'
      post 'configure', to: 'apps#configure_app', as: 'trigger_configure'
      get 'prepare'
      get 'publish'
      get 'runtime'
    end
  end
  root to: 'apps#index'

  mount ActionCable.server => '/cable'
end

app/models/notification.rb
class Notification < ApplicationRecord
  include ActionView::Helpers::DateHelper

  validates :title, presence: true
  validates :body, presence: true
  validates :url, presence: true

  validates :app, presence: true
  validates :user, presence: true

  belongs_to :app
  belongs_to :user

  belongs_to :rpush_app, class_name: 'Rpush::Client::ActiveRecord::App'
  belongs_to :rpush_notification, class_name: 'Rpush::Client::ActiveRecord::Notification', optional: true

  validate :url_contains_a_valid_deeplink
  after_validation :scrub_control_chars

  def scrub_control_chars
    self.title.gsub!(/[\u200B-\u200D\uFEFF]/, '')
    self.body.gsub!(/[\u200B-\u200D\uFEFF]/, '')
    self.url.gsub!(/[\u200B-\u200D\uFEFF]/, '')
  end

  def url_contains_a_valid_deeplink
    return if url.starts_with? 'http'
    items = JSON.parse(app.runtime)['navigation']['items']
    unless items.map { |x| x['component'] }.uniq.include? url
      errors.add(:url, 'contains a deep link which is not supported by this app.')
    end
  end

  def is_scheduled?
    new_record? || updated_at <= scheduled_for
  end

  def status
    rpush = rpush_notification

    if rpush
      return "processed #{time_ago_in_words(updated_at)} ago" if rpush.processing
      return "delivered #{time_ago_in_words(rpush.delivered_at)} ago" if rpush.delivered
      return "failed #{time_ago_in_words(rpush.failed_at)} ago" if rpush.failed
    end

    "scheduled for #{time_ago_in_words(scheduled_for)} from now"
  end

  def delivered?
    rpush_notification && rpush_notification.delivered
  end

  def failed?
    rpush_notification && rpush_notification.failed
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < AppAwareController
  before_action :authenticate_user!
  before_action :set_nofication_app
  before_action :set_notification, only: %i[show edit update destroy]

  authorize_actions_for :parent_resource, all_actions: :notify
  authorize_actions_for :parent_resource, actions: { configure_notifications: 'notify' }

  after_action :schedule_notification, only: %i[create update]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.where(app_id: @app.id).order('scheduled_for DESC, updated_at DESC').page params[:page]
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show; end

  # GET /notifications/new
  def new
    @notification = Notification.new
    respond_modal_with @notification
  end

  # GET /notifications/1/edit
  def edit
    respond_modal_with @notification
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)
    @notification.app = @app

    if params[:send] == 'now'
      @notification.update(scheduled_for: Time.now)
    else
      @notification.update(scheduled_for: Time.parse(notification_params['scheduled_for']).utc)
    end

    @notification.user = current_user
    @notification.rpush_app = @notification_app
    @notification.save

    respond_modal_with @notification, location: app_notifications_url
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    @notification.update(notification_params)

    if params[:send] == 'now'
      @notification.update(scheduled_for: Time.now)
    else
      @notification.update(scheduled_for: Time.parse(notification_params['scheduled_for']).utc)
    end

    respond_modal_with @notification, location: app_notifications_url
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to app_notifications_url, notice: 'Notifiation was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def configure_notifications
    if @notification_app.nil?
      api_key = settings_params['firebase_server_key']

      @notification_app = Rpush::Gcm::App.new
      @notification_app.name = @app.internal_id.to_s
      @notification_app.auth_key = api_key
      @notification_app.connections = 1
      @notification_app.save!
    end

    respond_to do |format|
      format.html { redirect_to app_notifications_url, notice: 'Settings was successfully applied.' }
      format.json { head :no_content }
    end
  end

  private

  def set_notification
    @notification = Notification.find(params[:id])
  end

  def set_nofication_app
    @notification_app = Rpush::Gcm::App.find_by_name(@app.internal_id.to_s)
  end

  def schedule_notification
    if @notification && @notification.valid?
      require 'sidekiq/api'

      jid = @notification.job_id

      if jid
        Sidekiq::ScheduledSet.new.find_job(jid).try(:delete)
        Sidekiq::Queue.new.find_job(jid).try(:delete)
      end

      job_id = NotificationWorker.perform_at(@notification.scheduled_for, @notification.id)
      @notification.update(job_id: job_id)
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def notification_params
    params.require(:notification).permit(
      :title,
      :body,
      :url,
      :send,
      :scheduled_for
    )
  end

  def settings_params
    params.require(:notification).permit(:firebase_server_key)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for([@app, notification], remote: request.xhr?, html: { data: { modal: true }}) do |f| %>
  <div class="modal-body">
  <% if notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notification.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul>
      <% notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, :class => "form-control" %>
  </div>

  <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, :class => "form-control", size: 3 %>
  </div>

  <div class="form-group">
      <%= f.label :url %>
      <%= f.url_field :url, :class => "form-control" %>
  </div>

  <div class="form-group btn-group btn-group-toggle" data-toggle="buttons">
    <%= label_tag(:send_now, "Send now", :class => "btn btn-outline-primary active", :id => "send_now") do %>
      <%= radio_button_tag(:send, "now", !notification.persisted? || !notification.is_scheduled? ) %> Send now
    <% end %>
    <%= label_tag(:send_later, "Send later", :class => "btn btn-outline-primary", :id => "send_later") do %>
      <%= radio_button_tag(:send, "later", notification.persisted? && notification.is_scheduled?) %> Send later
    <% end %>
  </div>

  <div class="panel-group" id="accordion">
      <div class="panel panel-default">
          <div id="chooseDatetime" class="panel-collapse collapse in">
              <div class="panel-body form-group">
                  <%= f.datetime_local_field :scheduled_for, class: 'form-control' %>
              </div>
          </div>
      </div>
  </div>

  <script>
      $(document).ready(function () {
          $("#send_now").click(function () {
              $("#chooseDatetime").collapse('hide');
          });
          $("#send_later").click(function () {
              $("#chooseDatetime").collapse('show');
          });
      });
  </script>
</div>

<div class="modal-footer">
  <%= f.submit :class => "btn btn-success" unless notification.delivered? %>
  <% end %>
  <%= button_to 'Delete', [notification.app, notification], method: :delete, data: { confirm: 'Are you sure?' }, :class => "mx-1 btn btn-outline-danger" if notification.persisted? %>
  <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
</div>

app/views/notifications/edit.html.erb
<% content_for :title, 'Editing notification' %>
<%= render 'form', notification: @notification %>

app/views/notifications/index.html.erb
<main>


<div class="form-group">
  <button class="btn btn-secondary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    Settings
  </button>

<div class="form-group collapse" id="collapseExample">
  <div class="card card-body">

    <div class="alert alert-secondary" role="alert">
      To send push notifications you need to set Firebase server key. To get it follow instructions on <a href="https://developer.clevertap.com/docs/find-your-fcm-sender-id-fcm-server-api-key#" target="_blank" class="alert-link">this link</a>.
    </div>

    <%= form_tag(app_notifications_configure_path, method: :post) do |f| %>
    <div class=" form-group">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <span class="input-group-text" id="basic-addon1">Firebase Server key:</span>
        </div>
          <%= text_field_tag "notification[firebase_server_key]", @notification_app.try(:auth_key) || "", :class => "form-control", :readonly => @notification_app.try(:auth_key) %>
          <div class="input-group-append">
            <%= submit_tag "Update", :class => "btn btn-success" unless @notification_app.try(:auth_key) %>
          </div>
        <div>
      </div>
    </div>
    <% end %>
  </div>
</div>

</div>

<div class="list-group">
  <%= link_to(new_app_notification_path, remote: true, data: { modal: true }, :class => 'list-group-item active justify-content-between') do %>
  <div class="d-flex w-100 justify-content-end align-items-center">
    <i class="fa fa-plus p-2" aria-hidden="true"></i>
    <span class="mr-auto p-2">Send new notification</span>
  </div>
  <% end %>
  <% @notifications.each do |notification| %>
  <%= link_to(edit_app_notification_path(notification.app, notification), remote: true, data: { modal: true }, :class=>'list-group-item list-group-item-action flex-column align-items-start') do %>
    <div class="d-flex w-100 justify-content-end">
      <h6 class="mr-auto"><%= notification.title %></h6>
      <%= content_tag(:small, notification.status, :class => class_string("text-danger" => notification.failed?)) %>
    </div>
      <%= content_tag(:small, notification.url, :class => "text-muted") %>
      <p class="mb-1"><%= notification.body %></p>
  <% end %>
  <% end %>
</div>

<div style="margin-top:36px;">
  <%= paginate @notifications %>
</div>


</main>

app/views/notifications/new.html.erb
<% content_for :title, 'Create new notification' %>
<%= render 'form', notification: @notification %>

app/views/notifications/show.html.erb
<% content_for :title, @notification.title %>
<%= render 'form', notification: @notification %>