config/routes.rb
Rails.application.routes.draw do
  post 'webhooks/receive'

  devise_for :users

  resources :apps do
    resources :assets do
      get 'download', action: 'download', as: 'download'
    end

    resources :notifications
    resources :versions

    post 'notifications/configure', to: 'notifications#configure_notifications'
    post 'autority/invite', to: 'apps#invite', as: 'autority_invite'

    member do
      get 'settings'
      get 'build'
      post 'build', to: 'apps#jenkins', as: 'trigger_build'
      post 'configure', to: 'apps#configure_app', as: 'trigger_configure'
      get 'prepare'
      get 'publish'
      get 'runtime'
    end
  end
  root to: 'apps#index'

  mount ActionCable.server => '/cable'
end

app/models/asset.rb
class Asset < ApplicationRecord
  extend FriendlyId
  include CopyCarrierwaveFile

  belongs_to :app
  before_destroy :internal_id

  mount_uploader :file, AssetsUploader

  validates_integrity_of :file
  validates_processing_of :file

  friendly_id :get_filename

  def duplicate_file(original)
    copy_carrierwave_file(original, self, :file)

    self.slug = original.slug
    self.save!
  end

  def internal_id(app_id = self.app_id)
    @internal_id = @internal_id || App.find(app_id).internal_id
  end

  private
  def get_filename
    self.file.filename
  end
end

app/controllers/assets_controller.rb
class AssetsController < AppAwareController
  before_action :authenticate_user!, except: [:download]

  before_action :set_asset, only: %i[show edit update destroy download]

  authorize_actions_for :parent_resource, all_actions: :build, except: :download

  # GET /assets
  # GET /assets.json
  def index
    @assets = @app.assets
  end

  # GET /assets/1
  # GET /assets/1.json
  def show; end

  # GET /assets/new
  def new
    @asset = Asset.new
    respond_modal_with @asset
  end

  # GET /assets/1/edit
  def edit
    respond_modal_with @asset
  end

  # POST /assets
  # POST /assets.json
  def create
    assets = []

    asset_params[:file].each do |file|
      asset = Asset.new(file: file, app_id: @app.id)
      assets << asset
    end

    assets.each do |asset|
      next if asset.save
      asset.errors.add(:base, :unprocessable_entity)
      respond_modal_with [@app, @asset], location: app_assets_url
      return
    end

    respond_modal_with [@app, @asset], location: app_assets_url
  end

  # PATCH/PUT /assets/1
  # PATCH/PUT /assets/1.json
  def update
    if @asset.update(file: asset_params[:file].first)
      respond_modal_with [@app, @asset], location: app_assets_url
    else
      @asset.errors.add(:base, :unprocessable_entity)
      respond_modal_with @asset
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.json
  def destroy
    @asset.destroy
    respond_to do |format|
      format.html { redirect_to app_assets_url, notice: 'Asset was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def download
    puts params
    if params[:variant].nil?
      redirect_to @asset.file.url
    else
      version = params[:variant]
      redirect_to @asset.file.versions[version.to_sym].url
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_asset
    @asset = Asset.friendly.find_by!(slug: params[:id] || params[:asset_id], app_id: @app.id)
  end

  def asset_params
    params.require(:asset).permit(file: [])
  end
end

app/helpers/assets_helper.rb
module AssetsHelper

  include ActionView::Helpers::AssetTagHelper

  def assets_content_type_icon(asset, size)
    case
    when asset.content_type.start_with?('image')
      image_tag('placeholder.png', size: size, :class => 'img-fluid preload', :data => { :source => asset.file.url })
    when asset.content_type.end_with?('json')
      '<i class="fa fa-file-code-o" style="font-size:32px"></i>'
    else
      '<i class="fa fa-font" style="font-size:32px"></i>'
    end
  end

  def asset_icon(asset, size)
    case
    when asset.content_type.start_with?('image')
      image_tag(asset.file.url, size: size, :class => 'img-fluid mx-auto d-block')
    when asset.content_type.end_with?('json')
      "<i class='fa fa-file-code-o' style='font-size:#{size}px'></i>"
    else
      "<i class='fa fa-font' style='font-size:#{size}px'></i>"
    end
  end
end

app/views/assets/_form.html.erb
<%= form_for([@app, asset], remote: request.xhr?, html: { data: { modal: true, multipart: true }}) do |f| %>

<%= hidden_field_tag :authenticity_token, form_authenticity_token %>

<div class="modal-body">
  <% if asset.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(asset.errors.count, "error") %>
      prohibited this asset from being saved:</h2>

    <ul>
      <% asset.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <% if asset.persisted? %>
  <%= raw asset_icon(asset, 64) %>
  <% end %>

  <div class="form-group">
    <%= f.label :file %>
    <%= f.file_field :file, :multiple => true, :class => "form-control-file" %>
  </div>

<% if asset.persisted? %>
<div class="form-group">
    <div class="btn-group" role="group" aria-label="Basic example">
      <% if @asset.content_type.start_with?('image') %>
      <%= link_to "Original", app_asset_download_path(:asset_id => @asset), :class => "btn btn-primary btn-sm", :target => '_blank' %>
  <% @asset.file.versions.each do |version| %>
    <%= link_to version.first, app_asset_download_path(:asset_id => @asset, :variant => version.first), :class => "btn btn-secondary btn-sm", :target => '_blank' %>
  <% end %>
  <% end %>
    </div>
</div>

</div>
<% end %>

<div class="modal-footer">
  <%= f.submit :class => "btn btn-success" %>
  <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
</div>
<% end %>

app/views/assets/edit.html.erb
<% content_for :title, 'Editing asset' %>
<%= render 'form', asset: @asset %>

app/views/assets/index.html.erb
<main>
  <div class="list-group">

    <%= link_to(new_app_asset_path, remote: true, data: { modal: true }, :class => 'list-group-item active justify-content-between') do %>
    <div class="d-flex w-100 justify-content-end align-items-center">
      <i class="fa fa-plus mr-2" aria-hidden="true"></i>
      <span class="mr-auto">Add new assets</span>
    </div>
    <% end %>
    <% @assets.each do |asset| %>
    <div class="list-group-item list-group-item-action flex-column">
      <div class="d-flex w-100 justify-content-end align-items-center">
        <%= link_to(edit_app_asset_path(@app, asset), remote: true, data: { modal: true }, :class=>'d-flex w-100') do %>
        <span class="mr-2"><%= raw assets_content_type_icon(asset, 32) %></span>
        <span class="mr-auto align-self-center"><%= asset.file_identifier %></span>
        <% end %>
        <div class="btn-group" role="group" aria-label="Asset actions">
          <%= link_to 'Edit', edit_app_asset_path(@app, asset), remote: true, data: { modal: true }, :class => "btn btn-sm btn-outline-primary" %>
          <%= link_to 'Delete', [@app, asset], method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-sm btn-outline-danger" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</main>

app/views/assets/new.html.erb
<% content_for :title, 'Create new asset' %>
<%= render 'form', asset: @asset %>

app/views/assets/show.html.erb
<% content_for :title, 'Showing asset' %>
<%= render 'form', asset: @asset %>