config/routes.rb
Rails.application.routes.draw do
  post 'webhooks/receive'

  devise_for :users

  resources :apps do
    resources :assets do
      get 'download', action: 'download', as: 'download'
    end

    resources :notifications
    resources :versions

    post 'notifications/configure', to: 'notifications#configure_notifications'
    post 'autority/invite', to: 'apps#invite', as: 'autority_invite'

    member do
      get 'settings'
      get 'build'
      post 'build', to: 'apps#jenkins', as: 'trigger_build'
      post 'configure', to: 'apps#configure_app', as: 'trigger_configure'
      get 'prepare'
      get 'publish'
      get 'runtime'
    end
  end
  root to: 'apps#index'

  mount ActionCable.server => '/cable'
end

app/views/apps/_build_list_android.html.erb
<section class="card">
    <div class="card-header">Android</div>
    <table class="card-block table table-hover" id="android">
        <thead>
            <tr>
                <th>App</th>
                <th>Status</th>
                <th>Details</th>
                <th>Step</th>
                <th>Message</th>
                <th>Updated</th>
            </tr>
        </thead>
        <tbody id="builds">
            <% @app.builds.where(platform: 'android').last(5).reverse.each do |build| %>
              <%= raw build_to_html_table_row(@app, build) %>
            <% end %>
        </tbody>
    </table>

    <div class="card-footer text-muted">
        <%= form_tag(trigger_configure_app_path, method: :post) do |f| %>
          <%= hidden_field_tag 'platform', 'android' %>
          <div class="row">
            <div class="col-8">
              <div class="form-check form-check-inline">
                <%= check_box_tag 'channels[]', 'fabric', true, :class => 'form-check-input' %>
                <%= label_tag 'channels[]', 'Fabric Beta', :class => 'form-check-label' %>
              </div>
              <div class="form-check form-check-inline">
                <%= check_box_tag 'channels[]', 'play', false, :class => 'form-check-input' %>
                <%= label_tag 'channels[]', 'Google Play', :class => 'form-check-label' %>
              </div>
            </div>
            <div class="col-4 text-right">
                <%= submit_tag 'Publish', :class => "btn btn-success", data: {disable_with: "Publishing..."} %>
            </div>
        <% end %>
    </div>
</section>

app/views/apps/_build_list_ios.html.erb
<section class="card">
    <div class="card-header">iOS</div>
    <table class="card-block table table-hover" id="ios">
        <thead>
            <tr>
                <th>App</th>
                <th>Status</th>
                <th>Details</th>
                <th>Step</th>
                <th>Message</th>
                <th>Updated </th>
            </tr>
        </thead>
        <tbody id="builds">
            <% @app.builds.where(platform: 'ios').last(5).reverse.each do |build| %>
              <%= raw build_to_html_table_row(@app, build) %>
            <% end %>
        </tbody>
    </table>

    <div class="card-footer text-muted">
      <%= form_tag(trigger_configure_app_path, method: :post) do |f| %>
      <%= hidden_field_tag 'platform', 'ios' %>
      <div class="row">
        <div class="col-8">
          <div class="form-check form-check-inline">
            <%= check_box_tag 'channels[]', 'appstore', true, :class => 'form-check-input' %>
            <%= label_tag 'channels[]', 'TestFlight / AppStore', :class => 'form-check-label' %>
          </div>
        </div>
        <div class="col-4 text-right">
          <%= submit_tag 'Publish', :class => "btn btn-success", data: {disable_with: "Publishing..."} %>
        </div>
      </div>
      <% end %>
    </div>
</section>

app/views/apps/_initial.html.erb
<%= form_for(app, remote: request.xhr?, html: { data: { modal: true }}) do |f| %>
<div class="modal-body">
<% if app.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(app.errors.count, "error") %>
        prohibited this app from being saved:</h2>

    <ul>
        <% app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="form-group">
    <%= f.label :internal_name %>
    <%= f.text_field :internal_name, :class => "form-control" %>
</div>

<% if app.new_record? and @apps.any? %>

<div class="form-group btn-group btn-group-toggle" data-toggle="buttons">
  <%= label_tag(:create_new, "Create new", :class => "btn btn-outline-primary active", :id => "create_new") do %>
    <%= radio_button_tag(:send, "now", true) %> Create new
  <% end %>
  <%= label_tag(:create_existing, "Clone existing one", :class => "btn btn btn-outline-primary", :id => "create_existing") do %>
    <%= radio_button_tag(:create, "existing") %> Clone an existing one
  <% end %>
</div>

<div class="panel-group" id="accordion">
    <div class="panel panel-default">
        <div id="chooseExistingApp" class="panel-collapse collapse in">
            <div class="panel-body form-group">
                <%= select_tag "origin", options_from_collection_for_select(@apps, :id, :internal_name), :class => "form-control" %>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $("#create_new").click(function () {
            $("#chooseExistingApp").collapse('hide');
        });
        $("#create_existing").click(function () {
            $("#chooseExistingApp").collapse('show');
        });
    });
</script>

<% end %>

</div>
<div class="modal-footer">
  <%= f.submit :class => "btn btn-success" %>
  <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
</div>
<% end %>

app/views/apps/_invite.html.erb
<%= content_tag :div, class: "modal fade", id: dom_id(@app, :modal) do %>
<%= form_tag app_autority_invite_path(@app) do %>
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabel">Invite user to <%= @app.internal_name %></h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="form-group">
        <%= label_tag 'app[invite]', "Email address", :class => "form-control-label" %><br/>
        <%= email_field_tag 'app[invite]', '', :class => "form-control" %>
      </div>
      <div class="form-group btn-group btn-group-toggle" data-toggle="buttons">
        <%= label_tag(:create_new, "Admin", :class => "btn btn-outline-primary active", :id => "role_admin") do %>
          <%= radio_button_tag(:role, "admin", true) %> Admin
        <% end %>
        <%= label_tag(:create_existing, "Push notification manager", :class => "btn btn btn-outline-primary", :id => "role_notifier") do %>
          <%= radio_button_tag(:role, "notifier") %> Push notification manager
        <% end %>
      </div>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      <%= submit_tag "Invite", method: :post, :class => "btn btn-success" %>
    </div>
  </div>
</div>
<% end %>
<% end %>

app/views/apps/_navigation.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
    <div class="container">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="<%= apps_path %>">Kolibri</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle navbar-brand" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <% if @app and not @app.new_record? %>
                        <%= @app.internal_name %>
                    <% else %>
                        Applications
                        <% end %>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <h6 class="dropdown-header">Applications</h6>
                        <% @apps.each do |application| %>
                        <%= link_to application.internal_name, edit_app_path(application), :class => "dropdown-item" %>
                        <% end %>
                        <div class="dropdown-divider"></div>
                        <%= link_to "Create new...", new_app_path, :class => "dropdown-item" %>
                    </div>
                </li>
                <% if @app and not @app.new_record? %>
                <li class="nav-item active">
                    <a class="nav-link" data-toggle="tab" href="#app" role="tab" aria-controls="app">App</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<%= app_assets_path(@app) %>" aria-controls="assets">Assets</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#build" role="tab" aria-controls="build">Build</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#store" role="tab" aria-controls="store">Store</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#publish" role="tab" aria-controls="publish">Publish</a>
                </li>
                <% end %>
            </ul>

            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <%= current_user.first_name %>
                        <%= current_user.last_name %>

                        <%= image_tag gravatar_url(current_user.email, 64), alt: "", :class => "nav-text img-responsive rounded-circle", :style => "max-height:20px; width:auto; vertical-align:middle;" %>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <%= link_to('Edit profile', edit_user_registration_path, :class => "dropdown-item") %>
                        <div class="dropdown-divider"></div>
                        <%= link_to('Logout', destroy_user_session_path, :method => :delete, :class => "dropdown-item") %>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/apps/_prepare.html.erb
<%= form_for(app) do |f| %>
<% if app.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(app.errors.count, "error") %>
        prohibited this app from being saved:</h2>

    <ul>
        <% app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<%= f.hidden_field :internal_name %>

<section class="card">
    <div class="card-header">
        Android
    </div>
    <div class="card-block">
        <div class=" form-group">
            <%= f.label "Bundle ID:" %><br/>
            <%= text_field_tag "app[android_config][bundle_id]", f.object.android_config["bundle_id"], :class => "form-control" %>
        </div>
    </div>
</section>

<section class="card">
    <div class="card-header">
        iOS
    </div>
    <div class="card-block">
      <div class=" form-group">
          <%= f.label "Bundle ID:" %><br/>
          <%= text_field_tag "app[ios_config][bundle_id]", f.object.ios_config["buncle_id"], :class => "form-control" %>
      </div>
    </div>
</section>

<section class="actions">
    <%= f.submit :class => "btn btn-primary" %>
</section>
<% end %>

app/views/apps/_settings.html.erb
<%= form_for(app) do |f| %>
<% if app.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(app.errors.count, "error") %>
        prohibited this app from being saved:</h2>

    <ul>
        <% app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<%= image_tag(app.android_icon.url, :size => "48") if app.android_icon? %>

<div class="form-group">
    <%= f.label :android_icon %>
    <%= f.file_field :android_icon, :class => "form-control-file", :'aria-describedby' => "fileHelp" %>
    <small id="fileHelp" class="form-text text-muted">This is some placeholder block-level help text for the above input. It's a bit lighter and easily wraps to a new line.</small>
</div>

<div class="form-group">
    <%= f.label :ios_icon %>
    <%= f.file_field :ios_icon, :class => "form-control-file", :'aria-describedby' => "fileHelp" %>
    <small id="fileHelp" class="form-text text-muted">This is some placeholder block-level help text for the above input. It's a bit lighter and easily wraps to a new line.</small>
</div>

<div class="form-group">
    <%= f.label :internal_name %>
    <%= f.text_field :internal_name, :class => "form-control" %>
</div>

<div class="form-group">
    <%= f.label :internal_id %>
    <%= f.text_field :internal_id, :readonly => true, :class => "form-control" %>
</div>

<div class="form-group">
    <%= f.label :runtime %>
    <%= f.text_area :runtime, :class => "jsoneditor-target form-control"%>
</div>
<div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
</div>
<% end %>

app/views/apps/build.html.erb
<main>
<%= form_for(@app) do |f| %>
<% if @app.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@app.errors.count, "error") %>
        prohibited this app from being saved:</h2>

    <ul>
        <% @app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<%= f.hidden_field :internal_name %>

<section class="card">
    <div class="card-header">
        Android
    </div>
    <div class="card-body">
        <div class="form-group">
            <%= f.label "Repository URL:" %><br/>
            <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">SSH:</span>
            </div>
            <%= text_field_tag "app[android_config][repository_url]", f.object.android_config["repository_url"], :'aria-describedby' => "basic-addon1", :class => class_string("form-control" => true, "is-valid" => !@app.android_config["repository_url"].blank?) %>
            <%= content_tag(:div, content_tag(:kbd, "git clone -b #{@app.internal_slug} --single-branch #{@app.android_config["repository_url"]}"), class: "valid-feedback") if !@app.android_config["repository_url"].blank? %>
            </div>
        </div>

        <div class=" form-group">
            <%= f.label "Publishing Profile:" %><br/>
            <%= select_tag "app[android_config][publishing_profile]", options_for_select(Rails.configuration.cockpit['publishing_profiles'].keys, f.object.android_config["publishing_profile"]), :class => "form-control" %>
        </div>

        <div class="alert alert-secondary" role="alert">
          On <a href="https://support.google.com/firebase/answer/7015592" target="_blank" class="alert-link">this link</a> you can find instructions how to get Firebase configuration for the app.
        </div>

        <div class="form-row">

          <div class="custom-file form-group col-md-10">
          <%= f.file_field :android_firebase, accept: 'application/json', :class => class_string("custom-file-input" => true, "is-valid" => !@app.android_firebase.file.nil?), :'aria-describedby' => "fileHelp" %>
          <%= f.label 'Android Firebase JSON file', :class => "custom-file-label" %>
          <%= content_tag(:div, content_tag(:p, "You have already uploaded an firebase configuration."), class: "valid-feedback") if !@app.android_firebase.file.nil? %>
          </div>

          <% unless @app.android_firebase.file.nil? %>
          <div class="form-group col-md-2">
            <a class="btn btn-success btn-block" href="<%= @app.android_firebase.url %>" target="_blank" role="button">Download</a>
          </div>
          <% end %>
        </div>
    </div>
</section>

<section class="card">
    <div class="card-header">
        iOS
    </div>
    <div class="card-body">
        <div class="form-group">
            <%= f.label "Repository URL:" %><br/>
            <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">SSH:</span>
            </div>
            <%= text_field_tag "app[ios_config][repository_url]", f.object.ios_config["repository_url"], :class => class_string("form-control" => true, "is-valid" => !@app.ios_config["repository_url"].blank?) %>
            <%= content_tag(:div, content_tag(:kbd, "git clone -b #{@app.internal_slug} --single-branch #{@app.ios_config["repository_url"]}"), class: "valid-feedback") if !@app.ios_config["repository_url"].blank? %>
            </div>
        </div>

        <div class=" form-group">
            <%= f.label "Publishing Profile:" %><br/>
            <%= select_tag "app[ios_config][publishing_profile]", options_for_select(Rails.configuration.cockpit['publishing_profiles'].keys, f.object.ios_config["publishing_profile"]), :class => "form-control" %>
        </div>

        <div class="alert alert-secondary" role="alert">
          On <a href="https://support.google.com/firebase/answer/7015592" target="_blank" class="alert-link">this link</a> you can find instructions how to get Firebase configuration for the app.
        </div>

        <div class="form-row">

          <div class="custom-file form-group col-md-10">
            <%= f.file_field :ios_firebase, :class => class_string("custom-file-input" => true, "is-valid" => !@app.ios_firebase.file.nil?), :'aria-describedby' => "fileHelp" %>
            <%= f.label 'iOS Firebase plist file', :class => "custom-file-label" %>
            <%= content_tag(:div, content_tag(:p, "You have already uploaded an firebase configuration."), class: "valid-feedback") if !@app.ios_firebase.file.nil? %>
          </div>

          <% unless @app.ios_firebase.file.nil? %>
          <div class="form-group col-md-2">
            <a class="btn btn-success btn-block" href="<%= @app.ios_firebase.url %>" target="_blank" role="button">Download</a>
          </div>
          <% end %>
        </div>
    </div>
</section>

<section class="actions">
    <%= f.submit :class => "btn btn-primary" %>
</section>
<% end %>
</main>

app/views/apps/index.html.erb
<main>
  <div class="list-group">
    <%= link_to(new_app_path, remote: true, data: { modal: true }, :class => 'list-group-item active justify-content-between') do %>
    <div class="d-flex w-100 justify-content-end align-items-center">
      <i class="fa fa-plus" aria-hidden="true"></i>
      <span class="mr-auto ml-2">Create new application</span>
    </div>
    <% end %>
    <% @apps.each do |app| %>

    <div class="list-group-item list-group-item-action d-flex flex-row justify-content-start">
      <%= link_to(edit_app_path(app), :class=>'w-100 mr-auto d-flex flex-row align-items-center') do %>
      <div class="">
        <% if app.icon? %>
        <%= image_tag('placeholder.png', size: "32", :class => "img-fluid preload", data: {source: app.icon.url}) %>
        <% else %>
        <%= image_tag('placeholder.png', size: "32", :class => "img-fluid")%>
        <% end %>
      </div>

      <div class="ml-2 mr-auto d-flex flex-column">
        <h6 class="mb-1"><%= app.internal_name %></h6>
        <%= content_tag(:small, "cloned from #{app.origin.internal_name}") if app.origin? %>
      </div>
      <% end %>

      <div class="ml-auto d-flex flex-row justify-content-end align-items-center">
        <div class="btn-group" role="group" aria-label="Asset actions">
          <%= link_to 'Invite', app_autority_invite_path(app), remote: true, method: :post, :class => "btn btn-sm btn-outline-secondary" if current_user.has_role? :admin, app %>
          <%= link_to 'Edit', edit_app_path(app), method: :get, :class => "btn btn-sm btn-outline-primary" %>
          <%= link_to 'Delete', app, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-sm btn-outline-danger" if current_user.has_role? :admin, app %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</main>

app/views/apps/invite.js.erb
$('body').append('<%= j render "apps/invite" %>');  // Append modal
$('#<%= dom_id @app, :modal %>').modal('toggle'); // Toggle modal

app/views/apps/new.html.erb
<% content_for :title, 'Create new application' %>
<%= render 'initial', app: @app %>

app/views/apps/notifications.erb
<main>
  <%= form_tag send_notifications_app_path(@app) do %>

  <section class="card">
    <div class="card-header">
      Settings
    </div>
    <div class="card-block">
      <div class=" form-group">
        <%= label_tag 'notification[firebase_server_key]', "Firebase Server key:" %><br/>
        <%= text_field_tag "notification[firebase_server_key]", @notification.try(:auth_key) || "", :class => "form-control", :readonly => @notification.try(:auth_key) %>
      </div>
    </div>
  </section>

  <section class="card">
    <div class="card-header">
      Notification
    </div>
    <div class="card-block">
      <div class=" form-group">
        <%= label_tag 'notification[url]', "URL", :class => "form-control-label" %><br/>
        <%= url_field_tag 'notification[url]', '', :class => "form-control" %>
      </div>

      <div class=" form-group">
        <%= label_tag 'notification[title]', "Title", :class => "form-control-label" %><br/>
        <%= text_field_tag 'notification[title]', '', :class => "form-control" %>
      </div>

      <div class=" form-group">
        <%= label_tag 'notification[message]', "Message", :class => "form-control-label" %><br/>
        <%= text_field_tag 'notification[message]', '', :class => "form-control" %>
      </div>
    </div>
    <div class="card-footer text-muted">
      <%= submit_tag "Send", method: :post, :class => "btn btn-success" %>
    </div>
  </section>
  <% end %>

  <section>

    <table class="table">
      <thead>
        <tr>
          <th>Status</th>
          <th>Details </th>
          <th>Data</th>
          <th>Notification</th>
        </tr>
      </thead>
      <tbody>
        <% @notifications.each do |notification| %>
        <tr>
          <td><%= notification.processing ? 'Processing' : notification.failed ? 'Failed' : 'Delivered'%></td>
          <td><pre><%= notification.error_description || "#{time_ago_in_words(notification.delivered_at) if notification.delivered_at}" %></pre></td>
          <td><code><%= notification.data.tap { |hs| hs.delete('to') } %></code></td>
          <td><code><%= notification.notification.tap { |hs| hs.delete('to') } %></code></td>
        </tr>
        <% end %>
      </tbody>
    </table>

  </section>
</main>

app/views/apps/publish.html.erb
<main>
<%= render 'build_list_android', app: @app %>
<%= render 'build_list_ios', app: @app %>
</main>

app/views/apps/settings.html.erb
<main>

<%= form_for(@app) do |f| %>
<% if @app.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@app.errors.count, "error") %>
        prohibited this app from being saved:</h2>

    <ul>
        <% @app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="form-group row">
    <div class="col-2 text-center"><%= image_tag('placeholder.png', :size => "72", :class => "img-fluid preload", data: {source: @app.android_icon.url}) if @app.android_icon? %></div>
    <div class="col-10">

      <div class="custom-file">
        <%= f.file_field :android_icon, :class => class_string("custom-file-input" => true), :'aria-describedby' => "fileHelp" %>
        <%= f.label :android_icon, :class => "custom-file-label" %>
        <small id="fileHelp" class="form-text text-muted">This is some placeholder block-level help text for the above input. It's a bit lighter and easily wraps to a new line.</small>
      </div>
    </div>
</div>

<div class="form-group row">
  <div class="col-2 text-center"><%= image_tag('placeholder.png', :size => "72", :class => "img-fluid preload", data: {source: @app.ios_icon.url}) if @app.ios_icon? %></div>
  <div class="col-10">
    <div class="custom-file">
      <%= f.file_field :ios_icon, :class => class_string("custom-file-input" => true), :'aria-describedby' => "fileHelp" %>
      <%= f.label :ios_icon, :class => "custom-file-label" %>
      <small id="fileHelp" class="form-text text-muted">This is some placeholder block-level help text for the above input. It's a bit lighter and easily wraps to a new line.</small>
    </div>
  </div>
</div>

<div class="form-group row">
  <div class="col-2 text-center"><%= image_tag('placeholder.png', :size => "128", :class => "img-fluid preload", data: {source: @app.splash.url}) if @app.splash? %></div>
  <div class="col-10">
    <div class="custom-file">
      <%= f.file_field :splash, :class => class_string("custom-file-input" => true), :'aria-describedby' => "fileHelp" %>
      <%= f.label :splash, :class => "custom-file-label" %>
      <small id="fileHelp" class="form-text text-muted">This is some placeholder block-level help text for the above input. It's a bit lighter and easily wraps to a new line.</small>
    </div>
  </div>
</div>

<div class="form-group">
    <%= f.label :internal_name, 'Name' %>
    <%= f.text_field :internal_name, :class => "form-control" %>
</div>

<div class="form-group">
    <%= f.label :internal_id, 'Id' %>
    <%= f.text_field :internal_id, :readonly => true, :class => "form-control" %>
</div>

<div class="form-group">
    <%= f.label :runtime %>
    <%= f.text_area :runtime, :class => "jsoneditor-target form-control"%>
</div>
<div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
    <%= link_to 'Changes history', app_versions_path(@app), :class => "btn btn-warning" %>
    <%= link_to 'Preview configuration', runtime_app_path(@app), :class => "btn btn-outline-primary", :target => '_blank' %>
    <%= link_to 'Invite', app_autority_invite_path(@app), remote: true, method: :post, :class => "btn btn-outline-primary" %>
</div>
<% end %>

</main>