config/routes.rb
Rails.application.routes.draw do
  post 'webhooks/receive'

  devise_for :users

  resources :apps do
    resources :assets do
      get 'download', action: 'download', as: 'download'
    end

    resources :notifications
    resources :versions

    post 'notifications/configure', to: 'notifications#configure_notifications'
    post 'autority/invite', to: 'apps#invite', as: 'autority_invite'

    member do
      get 'settings'
      get 'build'
      post 'build', to: 'apps#jenkins', as: 'trigger_build'
      post 'configure', to: 'apps#configure_app', as: 'trigger_configure'
      get 'prepare'
      get 'publish'
      get 'runtime'
    end
  end
  root to: 'apps#index'

  mount ActionCable.server => '/cable'
end

app/views/layouts/_bladefile.erb
# vim: syntax=yaml
# Uncomment below to specify your own resources.
# See https://github.com/jondot/blade for more information.
#

blades:
  <% if !app.ios_icon.file.nil? %>
  - source: blade/images/<%= app.ios_icon_identifier %>
    template: blade/templates/appicon.json
    out: Kolibri/Assets.xcassets/AppIcon.appiconset
    contents: true
  <% end %>
  <% if !app.splash.file.nil? %>
  - source: blade/images/<%= app.splash_identifier %>
    template: blade/templates/universal.json
    out: Kolibri/Assets.xcassets/LaunchImage.imageset
    contents: true
  <% end %>
  <% assets.each do |asset| %>
  - source: blade/images/<%= asset.file_identifier %>
    template: blade/templates/universal.json
    out: Kolibri/Assets.xcassets/<%= File.basename(asset.file_identifier, File.extname(asset.file_identifier)).camelize%>.imageset
    contents: true
  <% end %>

app/views/layouts/_fastlane.erb
fastlane_version "2.108.0"
default_platform :android

# Android
platform :android do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    ENV["KOLIBRI_URL"] = "https://kolibri.herokuapp.com"
    ENV["KOLIBRI_PROJECT"] = "<%= app.internal_id %>"
    ENV["CRYPTEX_GIT_BRANCH"] = "<%= app.android_config['publishing_profile'] || 'master' %>"
  end

  desc "Kolibri Pipeline (build, test and publish)"
  lane :all do

    kolibri(
      stage: "initialize",
      message: "Setup configuration and credentials before we go...",
    )

    cryptex(
      type: "export",
      out: "app/keystore.jks",
      key: "android_keystore",
      verbose: true
    )

    cryptex(
      type: "export",
      out: "google-play-console.json",
      key: "android_google_play",
      verbose: true
    )

    cryptex(
      type: "export_env",
      key: "android_keystore",
      set_env: true,
      verbose: true
    )

    build
    test
    publish
  end

  desc "Runs all the tests"
  lane :test do
    kolibri(
      stage: "test",
      message: "Running all the tests..."
    )

    gradle(task: "test")

    kolibri(
      stage: "test",
      message: "All tests passed.",
      code: 1
    )
  end

  desc "Build the project"
  lane :build do

    kolibri(
      stage: "build",
      message: "Building project..."
    )

    gradle(task: "assembleRelease", flags: "-q")

    kolibri(
      stage: "build",
      message: "Build successful",
      code: 1
    )
  end

  desc "Publish the app"
  lane :publish do

    <% if channels.include? 'fabric' %>

    kolibri(
      stage: "publish",
      message: "Publishing app to Fabric...",
    )

    crashlytics(
       api_token: "5b0e4ca8fe72e1ad97ccbd82e18f18ba4cacd219",
       build_secret: "8f94e66fae0366a48a613623166a2586ae77e7fab1b68d021471e0036ba46ad8"
    )

    kolibri(
      stage: "publish",
      message: "Successfully published to Fabric",
      code: 1
    )

    <% end %>

    sleep(10)

    <% if channels.include? 'play' %>

    kolibri(
      stage: "publish",
      message: "Publish app to Google Play as a Beta...",
    )

    supply(track: 'beta')

    kolibri(
      stage: "publish",
      message: "Application beta is published to Google Play",
      code: 1
    )

    <% end %>
  end

  after_all do |lane|
    slack(message: "Kolibri pipelane was successfully executed")
    update_fastlane
  end

  error do |lane, exception|

    error = %{Something goes wrong...
      #{exception.message}
    }

    kolibri(
      stage: lane.to_s,
      message: error,
      code: -1
    )

    slack(message: exception.message, success: false)
  end
end


# iOS
platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    ENV["KOLIBRI_URL"] = "https://kolibri.herokuapp.com"
    ENV["KOLIBRI_PROJECT"] = "<%= app.internal_id %>"

    ENV["MATCH_GIT_BRANCH"] = "<%= app.ios_config['publishing_profile'] || 'master' %>"
    ENV["MATCH_GIT_URL"] = "git@bitbucket.org:yanova/kolibri-certs.git"
    ENV["MATCH_TYPE"] = "appstore"
    ENV["MATCH_APP_IDENTIFIER"] = "<%= app.ios_config['bundle_id'] %>"
    ENV["MATCH_USERNAME"] = "<%= Rails.configuration.cockpit['publishing_profiles'][app.ios_config['publishing_profile']] %>"
  end

  desc "Kolibri Pipeline (build, test and publish)"
  lane :all do

    kolibri(
      stage: "initialize",
      message: "Setup provisioning and certificates before we go...",
    )

    keychain_entry = CredentialsManager::AccountManager.new(user: ENV['MATCH_USERNAME'] || '')

    produce(
      app_name: "<%= app.internal_name %>",
      app_identifier: "<%= app.ios_config['bundle_id'] %>",
      username:keychain_entry.user
    )

    match(
      type: "appstore",
      username: keychain_entry.user,
      app_identifier: "<%= app.ios_config['bundle_id'] %>",
    )

    build
    test
    publish
  end

  desc "Runs all the tests"
  lane :test do
    kolibri(
      stage: "test",
      message: "Running all the tests..."
    )

    scan(
      device: 'iPhone 6',
      scheme: "KolibriTests",
      clean: true
    )

    kolibri(
      stage: "test",
      message: "All tests passed.",
      code: 1
    )
  end

  desc "Build the project"
  lane :build do

    kolibri(
      stage: "build",
      message: "Building project..."
    )

    gym

    kolibri(
      stage: "build",
      message: "Build successful",
      code: 1
    )
  end

  desc "Publish the app"
  lane :publish do

    <% if channels.include? 'appstore' %>

    kolibri(
      stage: "publish",
      message: "Publish app TestFlight",
    )

    pilot(skip_waiting_for_build_processing: true)

    kolibri(
      stage: "publish",
      message: "Application beta is published to TestFlight",
      code: 1
    )

    <% end %>
  end

  after_all do |lane|
    slack(message: "Kolibri pipelane was successfully executed")
    update_fastlane
  end

  error do |lane, exception|

    error = %{Something goes wrong...
      #{exception.message}
    }

    kolibri(
      stage: lane.to_s,
      message: error,
      code: -1
    )

    slack(message: exception.message, success: false)
  end
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-toggleable-md navbar-dark bg-dark">
  <div class="container">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="<%= apps_path %>">Kolibri</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown align-self-center">
          <a class="nav-link dropdown-toggle navbar-brand" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if @app and not @app.new_record? %>
            <%= @app.internal_name %>
          <% else %>
            Applications
            <% end %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <h6 class="dropdown-header">Applications</h6>
            <% @apps.each do |application| %>
            <%= link_to application.internal_name, edit_app_path(application), :class => "dropdown-item" %>
            <% end %>
            <div class="dropdown-divider"></div>
            <%= link_to "Create new...", new_app_path, remote: true, data: { modal: true }, :class => "dropdown-item" %>
          </div>
        </li>
        <% if @app and not @app.new_record? %>
        <% if current_user.has_role? :admin, @app %>
        <li class="nav-item align-self-center <%= 'active' if controller?('apps') && action?('settings') || controller?('versions') %>">
          <a class="nav-link" href="<%= settings_app_path(@app) %>" aria-controls="app">App</a>
        </li>
        <% end %>
        <% if current_user.can_build?(@app) %>
        <li class="nav-item align-self-center <%= 'active' if controller?('assets') && action?('index', 'show', 'edit') %>">
          <a class="nav-link" href="<%= app_assets_path(@app) %>" aria-controls="assets">Assets</a>
        </li>
        <% end %>
        <% if current_user.can_build?(@app) %>
        <li class="nav-item align-self-center <%= 'active' if current_page?(build_app_path(@app)) %>">
          <a class="nav-link" href="<%= build_app_path(@app) %>" aria-controls="build">Build</a>
        </li>
        <% end %>
        <% if current_user.can_prepare?(@app) %>
        <li class="nav-item align-self-center <%= 'active' if current_page?(prepare_app_path(@app)) %>">
          <a class="nav-link" href="<%= prepare_app_path(@app) %>" aria-controls="store">Store</a>
        </li>
        <% end %>
        <% if current_user.can_publish?(@app) %>
        <li class="nav-item align-self-center <%= 'active' if current_page?(publish_app_path(@app)) %>">
          <a class="nav-link" href="<%= publish_app_path(@app) %>" aria-controls="publish">Publish</a>
        </li>
        <% end %>
        <% if current_user.can_notify?(@app) %>
        <li class="nav-item align-self-center <%= 'active' if current_page?(app_notifications_path(@app)) %>">
          <a class="nav-link" href="<%= app_notifications_path(@app) %>" aria-controls="publish">Notifications</a>
        </li>
        <% end %>
        <% end %>
      </ul>

      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.full_name %>
            <%= image_tag gravatar_url(current_user.email, 64), alt: "", :class => "nav-text img-responsive rounded-circle", :style => "max-height:36px; width:auto; vertical-align:middle;" %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to('Edit profile', edit_user_registration_path, :class => "dropdown-item") %>
            <div class="dropdown-divider"></div>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete, :class => "dropdown-item") %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notification.erb
<div class="alert alert-<%= type %> alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <%== message %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kolibri - Cockpit</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]> <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script> <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script> <![endif]-->

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= action_cable_meta_tag %>

    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
  </head>

  <body>

    <% if current_user %>
    <%= render 'layouts/navigation', application: @app, applications: @apps %>

    <div id="modal-holder"></div>

    <div id="notifications">
      <% if notice %>
      <div class="alert alert-info alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= notice %>
      </div>
      <% end %>

      <% if alert %>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= alert %>
      </div>
      <% end %>

      <% if danger %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= danger %>
      </div>
      <% end %>
    </div>
    <% end %>

    <%= yield %>

    <footer class="footer">
      <nav class="navbar fixed-bottom navbar-light bg-light">
        <span class="navbar-text">Version:
          <%= APP_VERSION %></span>
      </nav>
    </footer>
  </body>
</html>

app/views/layouts/modal.html.erb
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="mainModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="mainModalLabel">
          <%= yield :title if content_for? :title %>&nbsp;
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <%= yield %>
    </div>
  </div>
</div>